### ISSUE TITLE
I can't compile

### ISSUE THREAD

**Issue by yamachan249** [mapic91/MpcAsfTool#2]
I've set the freeimage variable as tutorial, but got this error when build
`ld.exe||cannot find -lfreeimage|`
`||error: ld returned 1 exit status|`

please help, thank you. @mapic91

**Comment by mapic91** [comment]
<img width="575" alt="Snipaste_2022-08-27_23-29-07" src="https://user-images.githubusercontent.com/3626810/187036914-5fab2506-39cf-4dc4-810a-2bab9b4fc51d.png">
<img width="560" alt="Snipaste_2022-08-27_23-30-26" src="https://user-images.githubusercontent.com/3626810/187036920-354f551d-6266-4280-b809-a6eb0146f6a9.png">
try this method

**Comment by yamachan249** [comment]
Thank you, problem solved.
